### ISSUE TITLE
.gitignoreにconfig.jsonを追記する

### ISSUE THREAD

**Issue by tegetege** [tapioka324/pybf#11]
private apiを利用するためにAPIKey,APISecretを書き込んだconfig.jsonを作ると思うんですが、一応のセキュリティとして.gitignoreに書き込んでいくのはいかがでしょうかー？

**Comment by tapioka324** [comment]
`config.json`は任意の場所に作成し呼び出せますが、開発者がこのリポジトリ内に作成することも想定されるので記載は必要だと思います。
